"""
Pydantic schemas for structured output validation in the Stock Signal Brief pipeline.
"""

from typing import List, Literal, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class StockAnalysisItem(BaseModel):
    """Structured analysis record for a single stock ticker."""
    ticker: str = Field(description="Uppercase stock ticker symbol (e.g. AAPL, NVDA, TSLA)")
    company_name: str = Field(description="Company name associated with the ticker")
    sentiment: Literal["BULLISH", "BEARISH", "NEUTRAL"] = Field(description="Market sentiment direction")
    confidence_score: float = Field(ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")
    key_themes: List[str] = Field(default_factory=list, description="Key market themes or drivers mentioned (e.g., earnings, AI demand)")
    recommendation: Literal["BUY", "WAIT"] = Field(default="WAIT", description="Actionable signal recommendation: BUY or WAIT")
    relevant_news: List[str] = Field(default_factory=list, description="All relevant news articles and transcript snippets found for ticker")
    extracted_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat(), description="ISO timestamp of extraction")


class StockAnalysisOutput(BaseModel):
    """Collection of analyzed stock items returned by Analysis Agent / Ollama."""
    items: List[StockAnalysisItem] = Field(default_factory=list, description="List of stock analysis records")
    total_tickers: int = Field(description="Total count of unique tickers identified")
    overall_market_mood: Literal["BULLISH", "BEARISH", "MIXED", "NEUTRAL"] = Field(description="Macro market mood across analyzed sources")
    processed_sources_count: int = Field(description="Number of raw source items analyzed")
    analysis_engine: str = Field(default="Ollama LLM", description="Engine used for analysis: Ollama LLM or Fallback Heuristic NLP")


class DailyStockBriefReport(BaseModel):
    """Final aggregated report generated by Orchestrator."""
    report_title: str = Field(default="Daily Autonomous Stock Signal Brief")
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    executive_summary: str = Field(description="High-level synthesis of market signals and top moves")
    top_bullish_signals: List[StockAnalysisItem] = Field(default_factory=list)
    top_bearish_signals: List[StockAnalysisItem] = Field(default_factory=list)
    macro_themes: List[str] = Field(default_factory=list)
    analysis_output: StockAnalysisOutput
